name: jfl2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  convert: ^3.0.1
  flutter_quill:
    path: ./flutter-quill-master
  async: ^2.4.2
  circular_menu: ^1.1.2
    # country_code_picker: ^2.0.1
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  currency_text_input_formatter: ^2.0.1
    # email_validator: '^1.0.6'
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.0
  push_notification: ^1.1.0
  flutter_keyboard_visibility: ^5.0.2
  firebase_crashlytics: ^2.1.1
  font_awesome_flutter: ^9.1.0
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  http: ^0.13.0
  openfoodfacts: ^1.3.2
  image_cropper: ^1.3.1
  image_picker: ^0.8.2
  drag_and_drop_gridview:
    git:
      url: https://github.com/DevOrbiter/drag_and_drop_gridview.git
      ref: master
  firebase_dynamic_links: ^2.0.6
  flutter_local_notifications: ^8.1.1
  auto_size_text:
    git:
      url: https://github.com/leisim/auto_size_text.git
      ref: master
  intl: ^0.17.0
  scroll_snap_list: ^0.8.2
  vimeoplayer:
    git:
      url: https://github.com/prilogy/vimeo_player.git
      ref: main
    #  chewie: ^1.0.0
    #  amazon_s3_cognito: ^0.5.2
  path: ^1.8.0
    #  flutter_ffmpeg: ^0.3.1
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  provider: 5.0.0
  pull_to_refresh: 2.0.0
  flutter_appauth: ^1.0.0+1
  table_calendar: ^3.0.1
  stripe_payment: ^1.0.6
  flutter_secure_storage: ^4.0.0
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^2.0.10
  marquee: ^2.2.0
    #  keyboard_visibility: ^0.5.6
  uuid: ^3.0.4
    #  pin_code_fields: ^6.1.0
    #  video_player: ^2.0.0
    #  video_thumbnail: ^0.2.5+1
    #  export_video_frame: ^0.0.5+4
  video_compress: ^2.1.1
    #  cloud_firestore: ^1.0.2
  country_code_picker: ^2.0.1
  email_validator: ^2.0.1
  url_launcher:
dependency_overrides:
    crypto: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - secrets.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
